version: "3.9"

services:
  db:
    image: postgres:15
    container_name: geo_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro   # только чтение
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    container_name: auth_service
    restart: always
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: "5000"                         # <-- важно: внутри слушаем 5000
    ports:
      - "${AUTH_PORT}:5000"

  photo-service:
    build: ./services/photo-service
    container_name: photo_service
    restart: always
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      UPLOAD_DIR: /uploads
      INSTALL_DIR: /app/install
      MODEL_DIR: /app/model
      PORT: "5000"                         # <-- уже было ок
    volumes:
      - ./uploads:/uploads
      - ./install:/app/install:ro
    ports:
      - "${PHOTO_PORT}:5000"

  coords-service:
    build: ./services/coords-service
    container_name: coords_service
    restart: always
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: "5000"                         # <-- важно
    ports:
      - "${COORDS_PORT}:5000"

  calc-service:
    build: ./services/calc-service
    container_name: calc_service
    restart: always
    environment:
      PORT: "5000"                         # <-- важно
    ports:
      - "${CALC_PORT}:5000"

  export-service:
    build: ./services/export-service
    container_name: export_service
    restart: always
    depends_on: [db]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: "5000"                         # <-- важно
      # лучше ссылаться на endpoint раздачи фото по UUID:
      PUBLIC_UPLOAD_BASE: "http://localhost:${PHOTO_PORT}/photos"
    ports:
      - "${EXPORT_PORT}:5000"

  api-gateway:
    build: ./services/api-gateway
    container_name: api_gateway
    restart: always
    depends_on:
      - auth-service
      - photo-service
      - coords-service
      - calc-service
      - export-service
    environment:
      AUTH_URL:   "http://auth-service:5000"
      PHOTO_URL:  "http://photo-service:5000"
      COORDS_URL: "http://coords-service:5000"
      CALC_URL:   "http://calc-service:5000"
      EXPORT_URL: "http://export-service:5000"
      PORT: "5000"                         # шлюз тоже слушает 5000 внутри
    ports:
      - "${GATEWAY_PORT}:5000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${FRONTEND_PORT}:80"




volumes:
  pgdata:
