FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# копируем код и статику
COPY app.py .
COPY static ./static

ENV PORT=5000
CMD ["python", "app.py"]
